/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const T = IDL.Record({
  'hireDate' : Time,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'department' : IDL.Text,
  'position' : IDL.Text,
});
export const T__1 = IDL.Record({
  'reviewDate' : Time,
  'notes' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const T__2 = IDL.Record({
  'checkIn' : IDL.Opt(Time),
  'checkOut' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func([T], [IDL.Nat], []),
  'addPerformanceReview' : IDL.Func([IDL.Nat, T__1], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func([IDL.Nat], [], []),
  'checkOut' : IDL.Func([IDL.Nat], [], []),
  'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getAttendance' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, T__2))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([IDL.Nat], [T], ['query']),
  'getPerformanceReviews' : IDL.Func([IDL.Nat], [IDL.Vec(T__1)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEmployees' : IDL.Nat,
          'todaysAttendanceCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEmployee' : IDL.Func([IDL.Nat, T], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const T = IDL.Record({
    'hireDate' : Time,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'department' : IDL.Text,
    'position' : IDL.Text,
  });
  const T__1 = IDL.Record({
    'reviewDate' : Time,
    'notes' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const T__2 = IDL.Record({
    'checkIn' : IDL.Opt(Time),
    'checkOut' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func([T], [IDL.Nat], []),
    'addPerformanceReview' : IDL.Func([IDL.Nat, T__1], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func([IDL.Nat], [], []),
    'checkOut' : IDL.Func([IDL.Nat], [], []),
    'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getAttendance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, T__2))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([IDL.Nat], [T], ['query']),
    'getPerformanceReviews' : IDL.Func([IDL.Nat], [IDL.Vec(T__1)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEmployees' : IDL.Nat,
            'todaysAttendanceCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEmployee' : IDL.Func([IDL.Nat, T], [], []),
  });
};

export const init = ({ IDL }) => { return []; };